language: python
python: 2.7
before_script:
  - pip install python-coveralls coverage
install:
  - pip install tox
  - python setup.py develop
env:
  # Django 1.7
  - TOX_ENV=py27-django1.7
  # Django 1.8
  - TOX_ENV=py27-django1.8
  # Django 1.9
  - TOX_ENV=py27-django1.9
script:
  - tox -e $TOX_ENV
  - coverage run --source=sepomex --omit=*/example/*,*/env_sepomex/*,*/migrations/* example/manage.py test

after_success:
  - COVERALLS_REPO_TOKEN=2qx9iBC9WPl5GJenVbuhzFff2KAlGDKJm coveralls
