language: python
python: 2.7
install:
  - pip install tox
env:
  # Django 1.7
  - TOX_ENV=py27-django1.7
  # Django 1.8
  - TOX_ENV=py27-django1.8
  # Django 1.9
  - TOX_ENV=py27-django1.9
script:
  - tox -e $TOX_ENV
